/*

   BLIS
   An object-based framework for developing high-performance BLAS-like
   libraries.

   Copyright (C) 2014, The University of Texas at Austin
   Copyright (C) 2020, The University of Tokyo

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are
   met:
    - Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    - Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    - Neither the name(s) of the copyright holder(s) nor the names of its
      contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
   HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


*/
// Kernel design only.
//
#define DGEMM_2VX12_INDEXED_MKER_LOOP_PLAIN_C_1(C0FH,C1FH,C2FH,C3FH,C4FH,C5FH,C6FH,C7FH,C8FH,C9FH,C10FH,C11FH,C0LH,C1LH,C2LH,C3LH,C4LH,C5LH,C6LH,C7LH,C8LH,C9LH,C10LH,C11LH,PT,ACOLFH,ACOLLH,BROW0,BROW1,BROW2,BROW3,BADDR,BRSBIT) \
  DGEMM_FMLA4_LD1RQD(C0FH,C1FH,C0LH,C1LH,PT,ACOLFH,ACOLLH,BROW0,BADDR,8) \
  DGEMM_FMLA4_LD1RQD(C2FH,C3FH,C2LH,C3LH,PT,ACOLFH,ACOLLH,BROW1,BADDR,10) \
" add             "#BADDR", "#BRSBIT", "#BADDR"   \n\t" /* B address forward. */ \
  DGEMM_FMLA4_LD1RQD(C4FH,C5FH,C4LH,C5LH,PT,ACOLFH,ACOLLH,BROW2,BADDR,0) \
  DGEMM_FMLA4_LD1RQD(C6FH,C7FH,C6LH,C7LH,PT,ACOLFH,ACOLLH,BROW3,BADDR,2) \
  \
  DGEMM_FMLA4_LD1RQD(C8FH,C9FH,C8LH,C9LH,PT,ACOLFH,ACOLLH,BROW0,BADDR,4) \
  DGEMM_FMLA4_LD1RQD(C10FH,C11FH,C10LH,C11LH,PT,ACOLFH,ACOLLH,BROW1,BADDR,6)

#define DGEMM_2VX12_INDEXED_MKER_LOOP_PLAIN_C_2(C0FH,C1FH,C2FH,C3FH,C4FH,C5FH,C6FH,C7FH,C8FH,C9FH,C10FH,C11FH,C0LH,C1LH,C2LH,C3LH,C4LH,C5LH,C6LH,C7LH,C8LH,C9LH,C10LH,C11LH,PT,ACOLFH,ACOLLH,BROW0,BROW1,BROW2,BROW3,BADDR,BRSBIT) \
  DGEMM_2VX12_INDEXED_MKER_LOOP_PLAIN_C_1(C0FH,C1FH,C2FH,C3FH,C4FH,C5FH,C6FH,C7FH,C8FH,C9FH,C10FH,C11FH,C0LH,C1LH,C2LH,C3LH,C4LH,C5LH,C6LH,C7LH,C8LH,C9LH,C10LH,C11LH,PT,ACOLFH,ACOLLH,BROW2,BROW3,BROW0,BROW1,BADDR,BRSBIT)

#define DGEMM_2VX12_INDEXED_MKER_LOOP_PLAIN_C_2_RESIDUAL(C0FH,C1FH,C2FH,C3FH,C4FH,C5FH,C6FH,C7FH,C8FH,C9FH,C10FH,C11FH,C0LH,C1LH,C2LH,C3LH,C4LH,C5LH,C6LH,C7LH,C8LH,C9LH,C10LH,C11LH,PT,ACOLFH,ACOLLH,BROW0,BROW1,BROW2,BROW3,BADDR,BRSBIT) \
  DGEMM_FMLA4_LD1RQD(C0FH,C1FH,C0LH,C1LH,PT,ACOLFH,ACOLLH,BROW2,BADDR,8) \
  DGEMM_FMLA4_LD1RQD(C2FH,C3FH,C2LH,C3LH,PT,ACOLFH,ACOLLH,BROW3,BADDR,10) \
" add             "#BADDR", "#BRSBIT", "#BADDR"   \n\t" /* B address forward. */ \
  DGEMM_FMLA2_INDEXED(C4FH,C5FH,ACOLFH,BROW0) \
  DGEMM_FMLA2_INDEXED(C4LH,C5LH,ACOLLH,BROW0) \
  DGEMM_FMLA2_INDEXED(C6FH,C7FH,ACOLFH,BROW1) \
  DGEMM_FMLA2_INDEXED(C6LH,C7LH,ACOLLH,BROW1) \
  \
  DGEMM_FMLA2_INDEXED(C8FH,C9FH,ACOLFH,BROW2) \
  DGEMM_FMLA2_INDEXED(C8LH,C9LH,ACOLLH,BROW2) \
  DGEMM_FMLA2_INDEXED(C10FH,C11FH,ACOLFH,BROW3) \
  DGEMM_FMLA2_INDEXED(C10LH,C11LH,ACOLLH,BROW3)

// Operations used in these kernels:
//
#define DGEMM_FMLA2_INDEXED(CCOL0,CCOL1,ACOL,BROW) \
" fmla  "#CCOL0".d, "#ACOL".d, "#BROW".d[0] \n\t" /* A[:, k] * B[0, k] */ \
" fmla  "#CCOL1".d, "#ACOL".d, "#BROW".d[1] \n\t" /* A[:, k] * B[1, k] */ \
  /*                                                This ":" can be either first or last half
   *                                                under current kernel design.
   */

#define DGEMM_FMLA4_LD1RQD(CCOL0FH,CCOL1FH,CCOL0LH,CCOL1LH,PT,ACOLFH,ACOLLH,BROW,BADDR,NSHIFT) \
  DGEMM_FMLA2_INDEXED(CCOL0FH,CCOL1FH,ACOLFH,BROW) \
  DGEMM_FMLA2_INDEXED(CCOL0LH,CCOL1LH,ACOLLH,BROW) \
" ld1rqd  "#BROW"."DT", "#PT"/z, ["#BADDR", #"#NSHIFT"*8]\n\t" \
  /* Note that here NSHIFT is the number of FP64 values.
   * Usually an even number should be passed.
   */

